spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/reserveme
    username: reserveme_user
    password: strongpassword
  flyway:
    schemas:
      - public
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate